### PR TITLE
Add bindings for Python3.

### PR DESCRIPTION
**Pull request by ahomansikka**
I copied folder python to python3 and converted files in folder python3 in such a way that python 3 understands them. Files example.py and tre-python.c had to be changed, file setup.py is not changed.

### CODE REVIEW

**Comment by cben** [comment]
@laurikari I've been using these py3 bindings from ahomansikka's fork(*) for over a year with no issues.  Can this be merged?

I see there are several long-open PRs here.  I assume your time is the bottleneck — is there way we can help? Would reviews from strangers help?

(*) if anyone else wants to use this, I've found it simplest to install an unmodified `libtre-dev` ubuntu package, then `setup.py install` from tre/python3 dir: https://github.com/anpc/sines-in-aging/blob/78baa94af343125d1ea916f3007b652ebc2d8cac/INSTALL/libraries.sh#L12-L19

**Comment by ahomansikka** [comment]
It seems @laurikari has abandoned this project.

**Comment by laurikari** [comment]
If someone wants to take up maintaining this project, let me know!

**Comment by Artoria2e5** [comment]
It might be interesting to do a [hpy](https://github.com/hpyproject/hpy) API port instead. This would allow tre to be used by many more Python implementations.

**Comment by trushworth** [comment]
A lot of these changes seem to have ended up in the python directory (as opposed to your python3 directory) before I started confusing things :).  I inadvertently added even more changes to the python directory so I could test the python extension under python3.  I am now going through your changes line by line to make sure I haven't missed any of them, and will likely merge them into the existing python directory (given python 2's EOL) as I find them.  It will take a few days for to examine and test things.

**Comment by trushworth** [comment]
I think I've managed to hand merge all these changes into the master branch.  I hope I've given credit correctly in the commit message  Thank you for the improvements!

**Pull request closed without merging**
