### PR TITLE
Long pattern strings

### PR DESCRIPTION
**Pull request by adamfeuer**
This pull request adds two configure options via environment variables:
- `TRE_EXPRESSION_STACK_SIZE_IN_BYTES`
- `TRE_EXPRESSION_RING_BUFFER_SIZE_IN_BYTES`

This allows the user to compile tre with much large stack and ring buffer sizes, if needed to parse very large pattern strings.

The expression ring buffer is still statically allocated.

A `PACKAGING.md` file is also added with instructions on how to build a distribution package.

(I'm using tre in a project that needs fuzzy matching with very large pattern strings - hence this changeset.)

### CODE REVIEW

**Comment by pombredanne** [comment]
@adamfeuer This sounds really useful for a possible case of mine....  what do you mean by very large patterns? How big?
And what would be the recipe to decide on the values for `TRE_EXPRESSION_STACK_SIZE_IN_BYTES` and `TRE_EXPRESSION_RING_BUFFER_SIZE_IN_BYTES` ? How would this relate to the size of one pattern? or many patterns?

**Comment by adamfeuer** [comment]
@pombredanne For us large patterns mean many kilobytes, even hundreds of kilobytes. When we compiled we just hard coded the sizes in the two settings variables you mentioned. We were running on a high-ram AWS EC2 instance so memory wasn't a problem.

But because I haven't heard back from the maintainer of this project for months, we decided to remove our uses of tre from our project... and have been looking at other alternatives. We're probably going to write something custom that matches our use case directly.

**Comment by pombredanne** [comment]
@adamfeuer Thank you for the quick response! I am looking for a faster alternative to a rather naive ngrams inverted index structure I use in https://github.com/nexB/scancode-toolkit for license detection. Patterns range from a few bytes up to 100KB and there are about 4000 of these and growing.
We could join forces if our use cases share some similarities...

**Comment by pombredanne** [comment]
@laurikari It looks like do not have a lot of time for tre.... do you?

**Comment by adamfeuer** [comment]
@pombredanne Let's talk about collaborating in email. My team is using python, so our solution will be a python module (though it may be programmed in another language and exported as a python module). It looks like you use python too. My email is on my github profile page.

**Pull request closed without merging**
